language: node_js
node_js:
  - "6.1"
  - "6"
  - "5.1"
  - "5"
  - "4.2"
  - "4.1"
  - "4.0"
before_install:
  - npm install -g typings
install:
  - npm install
  - typings install
script:
  - npm run-script lint
  - npm test
