language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
  - "5"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn build
  - yarn test:coverage
  - yarn coveralls
